# Generated by Django 4.2.3 on 2023-08-22 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0003_book_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='cost',
            new_name='rental_cost',
        ),
    ]
